name: examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example-and-coverage:
    name: example and coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: coverage.out
          outfile: coverage.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
